language: python
addons:
  apt:
    packages:
    - zlib1g-dev
    - libblas-dev
    - liblapack-dev
    - libgfortran-4.8-dev
    - libncurses5-dev
    - r-base
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
python:
  - "3.4"
sudo: false
install:
  - "source ./install_dependencies.sh"
script:
  - "python setup.py test"
